### ISSUE TITLE
The spotify swap service has been updated with the new Beta

### ISSUE THREAD

**Issue by Zwaaan** [chrismlarson/spotify-token-swap-gae#1]
Hi!

First, I love the work you have put up, I've no clue on the python part so it was a blessing to just copy this and use Google App Engine.

However, since the latest beta (one week ago) the spotify token swap service is out of date. I would be really happy if you could update the code to match the new service!

BR
Jonas

**Comment by chrismlarson** [comment]
Everything should be updated to work with beta 3. The refreshing of the token might not work just yet because it's a bit harder to test, but this should be resolved. :smile:

**Comment by Zwaaan** [comment]
Chris, you made my day! Nice work my friend!! :)

**Comment by chrismlarson** [comment]
Yep, just did a quick check. The refresh stuff is working. This should be good to go.

**Comment by Zwaaan** [comment]
Hi again!

They now encrypt the token in the app so I guess the service needs to be
updated again :S I don't get a proper JSON object from the server anymore.
Would be extremely happy if you could have a look since I don't know what
to change :)

Cheers,
Jonas

2014-08-08 21:22 GMT+02:00 Chris Larson notifications@github.com:

**Comment by markusbergh** [comment]
+1

:)

**Comment by chrismlarson** [comment]
Right on. I'll take a look at the latest release soon. I've been out of town.

**Comment by Zwaaan** [comment]
Great! Do you know when that might be? I'm planning on releasing my app
soon so would be really helpful! :)

Best regards
Jonas

2014-12-02 22:38 GMT+01:00 Chris Larson notifications@github.com:

**Comment by chrismlarson** [comment]
I'll take another look tonight and see if I can get a fix. :) It didn't
look too complicated. I haven't played around with encryption much and they
are using that now, so I couldn't fix it when I first looked at it. But
I'll sit down and do it tonight (EST).

**Comment by Zwaaan** [comment]
Thanks a lot! Really appreciate it! :)

**Comment by chrismlarson** [comment]
Looks like it should be up and working again. You just need a new random string for the encryption. Just something you need to create, nothing that you need to get from Spotify Dev. Create something here: http://www.random.org/strings/

**Comment by Zwaaan** [comment]
Finally released my fitness app Runify, check it out if you want! :)

Just wanted to say thanks again for all help, your token service is awesome!

BR
Jonas
Runify

2014-12-12 6:24 GMT+01:00 Chris Larson notifications@github.com:

**Comment by chrismlarson** [comment]
Oh man... that login experience. :smile: so sweet.

It's a neat little app, I'll have to actually try it out when things thaw out around here!
