### ISSUE TITLE
Refresh doesn't work with beta 6

### ISSUE THREAD

**Issue by Zwaaan** [chrismlarson/spotify-token-swap-gae#3]
With the latest Spotify SDK beta 6, the refresh doesn't work anymore.

It's probably related to that the encryption is now made in the app and not on the server.

BR
Jonas

**Comment by chrismlarson** [comment]
Should be fixed with e15922e4a9cedb81c9c542cdf45a0186e6e34eb4 :)

**Comment by Zwaaan** [comment]
Great, thanks man!

I uploaded it but I don't quite get it working.

When I login with Spotify I get a session object back. But when I look in
it the isValid is YES, but the expirationDate is the same as current time
:S So first time I try to fetch the playlist it works, but If I try to do
it again 2 seconds after or so, I get an internal server error 500.

Do you have any idea why that might be?

I've usen the Spotify Simple Track as an example. Tried to fix it all day
with no success :(

Best regards
Jonas

2014-12-12 6:27 GMT+01:00 Chris Larson notifications@github.com:

**Comment by Zwaaan** [comment]
Can it be that the session is not swapped correctly or something? Refresh
the token doesn't work.

2014-12-12 20:10 GMT+01:00 Jonas Nolte jonas.m.nolte@gmail.com:

**Comment by chrismlarson** [comment]
Weird. I'll give it a look. I was testing it with the Spotify Simple Track
as well.

**Comment by chrismlarson** [comment]
I tried it again and I'm seeing it having an expiration date an hour from
when I first get the session back. Maybe it was a glitch with their system?
Are you still having issues?
http://content.screencast.com/users/ChrisLarson/folders/Snagit/media/8c040bd6-a88e-404b-98d2-f6b12241e514/2014-12-13_18-04-59.png

**Comment by Zwaaan** [comment]
Hi! I found the issue :) I forgot to send the flag for read playlists in
the scope, and spotify handled that with sending me 500 internal server
error :) thabk you so much for all the help!

By the way, are you working on a spotify app? Let me know when its out in
that case! :)

**Comment by chrismlarson** [comment]
That's great news!

I had one in the works, but I'm working on another project currently. I'm
really waiting until they give us some more playlist creation control in
the API before I work on the app much more. :/
